name: 提出新功能
description: 为 Aurona Code 提供新功能的建议
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您为 Aurona Code 提出新功能建议
        我们会优先考虑契合项目核心理念的功能
  - type: textarea
    id: problem
    attributes:
      label: 该功能请求是否与某个痛点相关
      description: 请简练地描述目前的痛点是什么（例如当我试图执行某操作时总是觉得很繁琐）
      placeholder: 请在此处描述痛点...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: 描述您期望的解决方案
      description: 请清晰地描述您希望通过什么方式解决上述痛点
      placeholder: 请在此处描述您的解决方案...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 描述您曾考虑过的替代方案
      description: 简练地描述您曾经考虑过的其他可行的替代方案或功能
  - type: textarea
    id: context
    attributes:
      label: 附加背景上下文
      description: 请在此处补充与该功能请求相关的任何其他上下文或截图
