// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GitCommit } from "./GitCommit";
import type { GitFile } from "./GitFile";

export type GitFullStatus = { repo_path: string, is_repo: boolean, files: Array<GitFile>, commits: Array<GitCommit>, branch: string, };