// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlatformInfo = { operatingSystem: string, architecture: string, family: string, defaultShell: string | null, desktopSession: string | null, pathRestored: boolean, };