// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SearchResult = { file_path: string, line_number: number, match_text: string, index: number, };