import fs from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const audit = JSON.parse(fs.readFileSync(path.join(root, "scripts/data/audit-0.4.14.json"), "utf8"));
const groups = [
  ["文件", ["P0-01", "P1-01", "P1-02", "P1-03", "P1-04", "P2-01"]],
  ["Git", ["P1-05", "P1-06", "P2-02", "P2-03"]],
  ["工具链", ["P1-07", "P1-08", "P1-09", "P2-04", "P2-05"]],
  ["语言服务", ["P1-10", "P1-11", "P2-06", "P2-07", "P2-08"]],
  ["调试", ["P1-12", "P1-13", "P2-09"]],
  ["终端", ["P2-10", "P2-11", "P2-12"]],
  ["AI", ["P0-02", "P1-20", "P1-21"]],
  ["Agent", ["P1-22", "P1-23", "P3-03", "P3-04"]],
  ["扩展宿主", ["P1-14", "P1-15", "P1-16", "P2-13", "P2-14"]],
  ["资源安全", ["P0-04", "P1-17", "P3-05"]],
  ["Marketplace", ["P1-18", "P1-19", "P2-15", "P2-16", "P2-17"]],
  ["系统与发布", ["P0-03", "P1-24", "P3-01", "P3-02"]],
];
const labels = { pending: "待实施", "in-progress": "实施与验收中", implemented: "待验收", verified: "已验收", "external-blocked": "生产验证阻塞" };
const releasedScope = audit.releaseScope;
const byId = new Map(audit.items.map((item) => [item.id, item]));
const sections = groups.map(([title, ids]) => ({ title,
  description: releasedScope ? "本版实现；剩余验收与外部依赖转入 0.4.15，详见状态矩阵。" : "0.4.14 开发记录，状态以逐项验收矩阵为准。", auditIds: ids,
  items: ids.map((id) => {
    const item = byId.get(id);
    if (!item) throw new Error(`Missing audit item ${id}`);
    return releasedScope ? `${item.title}：${item.userVisible ?? item.title}` : `${item.title}：${item.userVisible ?? item.title}（${labels[item.status]}）。`;
  }),
}));
const entry = { version: "V0.4.14", date: audit.freezeDate ?? "2026-10-06", isLatest: true,
  summary: releasedScope ? "0.4.14 安全、稳定性与性能更新：包含 50 项实现，剩余完整验收和生产 Marketplace 签名对接转入 0.4.15；未宣称全部验收完成。" : "0.4.14 安全、稳定性与性能开发版本：50 项逐项跟踪；尚未完成验收，不具备发布资格。", sections };
fs.writeFileSync(path.join(root, "Src/Features/Settings/AuditChangelogData.ts"),
  `// Generated by scripts/sync-audit-0.4.14.mjs from the audited status matrix.\nimport type { ChangelogEntry } from "./ChangelogData";\n\nexport const AUDIT_0414_CHANGELOG: ChangelogEntry = ${JSON.stringify(entry, null, 2)};\n`);
const rows = audit.items.map((item) => `| ${item.id} | ${item.title} | ${item.status} | ${item.implementation.join("<br>") || "Pending"} | ${item.validation.join("<br>") || "No acceptance evidence"} | ${item.notes.join("<br>") || "-"} |`);
fs.writeFileSync(path.join(root, "Docs/0.4.14-Implementation-Status.md"),
  `# V0.4.14 Implementation Status\n\nBaseline: \`${audit.baseline}\` (V0.4.13). Version: \`0.4.14\`. Release freeze: ${audit.freezeDate ?? "not frozen"}.\n\nGenerated from \`scripts/data/audit-0.4.14.json\`. Code, automated validation, desktop acceptance and production dependencies are tracked separately. No item is verified merely because its code compiles.\n\n${releasedScope ? "The maintainer approved a formal release with remaining acceptance carried into [0.4.15](0.4.15-Carryover-Plan.md). All statuses and evidence below are preserved; see [Release Decision](0.4.14-Release-Decision.md).\n\n" : ""}| ID | Item | Status | Implementation | Validation | Remaining Work |\n| --- | --- | --- | --- | --- | --- |\n${rows.join("\n")}\n\nProduction acceptance requires official updater signing provenance and Marketplace signed metadata. Test keys and fixtures cannot clear these dependencies. ${releasedScope ? "Publication requires matching Quality success and actual candidate hashes/signatures verified against the pinned updater key. Carryover does not bypass runtime security checks." : "No tag, upload or publication is authorized by this local milestone."}\n`);
if (releasedScope) {
  const carried = releasedScope.carryoverIds.map((id) => byId.get(id));
  const carryRows = carried.map((item) => `| ${item.id} | ${item.title} | ${item.status} | ${item.notes.join("<br>")} |`);
  fs.writeFileSync(path.join(root, releasedScope.carryoverDocument),
    `# V0.4.15 Carryover Plan\n\nOn ${releasedScope.approvedOn}, the maintainer approved formal publication of 0.4.14 and assigned the remaining work to 0.4.15. This is a scope decision, not evidence of completed acceptance. Original IDs, implementation and validation remain in [0.4.14 Implementation Status](0.4.14-Implementation-Status.md).\n\n## Priority and Acceptance\n\nComplete P0 production provenance and native workflow evidence first, then P1 security/fault workflows, P2 lifecycle/performance and P3 recovery/resource evidence. The 47 in-progress items and three external-blocked items retain their original acceptance criteria. Never change them to verified without evidence. Marketplace integration requires production signed package descriptors and catalogs from its separate service; unsigned remote installation remains blocked. Compare optimized installers against the fixed performance baseline and preserve the original negative tests and quotas.\n\n| ID | Item | Original Status | Remaining Work for 0.4.15 |\n| --- | --- | --- | --- |\n${carryRows.join("\n")}\n\n## Evidence to Deliver\n\nRecord native authorization/cancellation, actual provider/LSP/DAP/interpreter and extension flows, disk/keyring failure, concurrent path replacement, process-tree cleanup and crash recovery. Finish 100-cycle resource trends, inactive Canvas counters, complete language review and optimized cross-platform performance comparisons. Production signing fixtures do not substitute for actual artifacts or Marketplace data.\n`);
}
console.log("Synchronized all 50 audit records and 12 changelog sections.");
