// Centralized Icon Engine
import { 
  IconFolder, 
  IconFolderOpen, 
  IconChevronRight, 
  IconFile, 
  IconMenu2, 
  IconSearch, 
  IconGitBranch, 
  IconPuzzle, 
  IconBell, 
  IconSettings,
  IconX,
  IconMinus,
  IconSquare,
  IconFileCode,
  IconLayoutSidebarLeftCollapse,
  IconCrop11,
  IconSquares,
  IconBrandGithub,
  IconSparkles,
  IconFiles,
  IconFilePlus,
  IconFolderPlus,
  IconRefresh,
  IconAlertTriangle,
  IconPalette,
  IconMoon,
  IconSun,
  IconDeviceDesktop,
  IconPlus,
  IconChevronDown,
  IconCloudUpload,
  IconCloudDownload,
  IconChecks,
  IconTrash,
  IconBrandTypescript,
  IconBrandJavascript,
  IconBrandPython,
  IconBrandCss3,
  IconBrandHtml5,
  IconJson,
  IconMarkdown,
  IconPhoto,
  IconInfoCircle,
  IconFileText,
  IconDeviceFloppy,
  IconTerminal2,
  IconHistory,
  IconGitCommit,
  IconLayoutBottombar,
  IconLayoutBottombarFilled,
  IconList,
  IconPlayerPlayFilled,
  IconEraser
} from "@tabler/icons-react";

export const Icons = {
  // Navigation & Shell
  Menu: IconMenu2,
  Search: IconSearch,
  Git: IconGitBranch,
  GitBranch: IconGitBranch,
  Plus: IconPlus,
  ChevronDown: IconChevronDown,
  Push: IconCloudUpload,
  Pull: IconCloudDownload,
  Checks: IconChecks,
  Trash: IconTrash,
  Extensions: IconPuzzle,
  
  // File Types
  FileTs: IconBrandTypescript,
  FileJs: IconBrandJavascript,
  FilePy: IconBrandPython,
  FileCss: IconBrandCss3,
  FileHtml: IconBrandHtml5,
  FileJson: IconJson,
  FileMd: IconMarkdown,
  FileImage: IconPhoto,
  Bell: IconBell,
  Settings: IconSettings,
  SidebarToggle: IconLayoutSidebarLeftCollapse,

  // Window Controls
  Close: IconX,
  Minimize: IconMinus,
  Maximize: IconCrop11,
  Restore: IconSquares,
  Minus: IconMinus,

  // File Explorer
  Folder: IconFolder,
  FolderOpen: IconFolderOpen,
  File: IconFile,
  ChevronRight: IconChevronRight,
  FilePlus: IconFilePlus,
  FolderPlus: IconFolderPlus,
  Refresh: IconRefresh,
  
  // Editor
  FileCode: IconFileCode,
  Save: IconDeviceFloppy,

  // Activity Bar
  Github: IconBrandGithub,
  Sparkles: IconSparkles,
  Files: IconFiles,
  
  // Others
  AlertTriangle: IconAlertTriangle,
  Paintbrush: IconPalette,
  Palette: IconPalette,
  Sun: IconSun,
  Moon: IconMoon,
  Monitor: IconDeviceDesktop,
  Info: IconInfoCircle,
  FileText: IconFileText,
  Terminal: IconTerminal2,
  History: IconHistory,
  GitCommit: IconGitCommit,
  BottomPanel: IconLayoutBottombar,
  BottomPanelFilled: IconLayoutBottombarFilled,
  List: IconList,
  Play: IconPlayerPlayFilled,
  Eraser: IconEraser
};
